services:
  servizo1:
    image: httpd
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/usr/local/apache2/htdocs
  servizo2:
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - .env

#    volumes:
#      - datosbd:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:8080
    environment:
      - PMA_ARBITRARY=1
      # - PMA_HOST=servizo2
volumes:
  datosbd:


## secret incompleto
## secrets:
##  my_secret: