services:
  servizo1:
    image: httpd
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/usr/local/apache2/htdocs
  servizo2:
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - .env
#    environment:
#      - MYSQL_ROOT_PASSWORD=abc123.
#      - MYSQL_DATABASE=db1
#      - MYSQL_USER=a22jorgebb
#      - MYSQL_PASSWORD=abc123.
    volumes:
      - datosbd:/var/lib/mysql
volumes:
  datosbd: